### ISSUE TITLE
rocgdb not working due to missing libpython3.8 library

### ISSUE THREAD

**Issue by codemk8** [amddcgpuce/AMDAcceleratorCloudGuides#22]
Partition: 1CN96C8G1H_4IB_MI250_Ubuntu22

$ module load rocm-5.7.1
$ rocgdb 
rocgdb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

Tried a few other rocm modules, got the same error

**Comment by amddcgpuce** [comment]
@codemk8 
Could you try to use ROCm docker with `podman` and use `rocgdb`?
Here's how to guide: https://github.com/amddcgpuce/AMDAcceleratorCloudGuides/blob/8787dca64fa33240e1e7d6b3397cdd806b93b182/AACPlanoSlurmCluster/HowToGuides/How%20to%20Use%20Podman%20on%20AMD%20Accelerator%20Cloud%20to%20Use%20rocgdb%20to%20Debug%20Application.pdf

@sanjtrip @ozziemoreno @sidamd @jagadish-amd @amddcgpuce

**Comment by codemk8** [comment]
the `podman` worked.
