### ISSUE TITLE
How is it possible to run a webserver on an application?

### ISSUE THREAD

**Issue by smilenaderi** [amddcgpuce/AMDAcceleratorCloudGuides#30]
Is it possible to run a web application on a specific port?

**Comment by smilenaderi** [comment]
@amddcgpuce

**Comment by amddcgpuce** [comment]
@sanjtrip @ozziemoreno @michael-franklin-amd Could you please watch the issues and discussions and respond to questions?
CC: @jagadish-amd

**Comment by jsevillaamd** [comment]
AAC won't allow custom web applications, because of security reasons
